name = "Ole Kristian Dyskeland"
license = "MIT"
licenselink = "https://github.com/HugoBlox/theme-academic-cv/blob/main/LICENSE.md"
description = "Use the no-code website framework to easily build your site. Choose from 50+ widgets and deploy with one click! Fully personalize your site with themes, plugins, and language packs."
homepage = "https://dyskeland.no"
demosite = "https://dyskeland.no/"
tags = ["Ole Kristian Dyskeland"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Ole Kristian Dyskeland"
  homepage = "https://dyskeland.no"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
